-- Schema que o Hibernate criava com ddl-auto. O "if not exists" deixa esta
-- migration passar em bancos criados antes do Flyway (baseline na versão 0).
create table if not exists pauta (
    id bigint generated by default as identity primary key,
    titulo varchar(255) not null,
    descricao text not null,
    tempo_limite_em_aberto timestamp(6),
    minutos_em_aberto bigint,
    is_cancelado boolean not null,
    motivo_cancelamento text
);

create table if not exists voto_sessao_pauta (
    id bigint generated by default as identity primary key,
    voto_positivo boolean,
    cpf varchar(11),
    id_pauta bigint not null references pauta (id)
);
